export enum FormWidgetType {
    AUTOCOMPLETE = 'autocomplete',
    CHECKBOX = 'checkbox',
    CHECKBOXSET = 'checkboxset',
    CHIPS = 'chips',
    COLORPICKER = 'colorpicker',
    CURRENCY = 'currency',
    DATE = 'date',
    DATETIME = 'datetime',
    NUMBER = 'number',
    PASSWORD = 'password',
    RADIOSET = 'radioset',
    RATING = 'rating',
    RICHTEXT = 'richtext',
    SELECT = 'select',
    TOGGLE = 'toggle',
    SLIDER = 'slider',
    SWITCH = 'switch',
    TEXT = 'text',
    TEXTAREA = 'textarea',
    TIME = 'time',
    TIMESTAMP = 'timestamp',
    TYPEAHEAD = 'typeahead',
    UPLOAD = 'upload'
}