image: node:latest
stages:
   - setup
   - build
   - test

cache:
  paths:
    - node_modules/

 setup:
  stage: setup
  script:
    - npm install -g @angular/cli
    - npm install
    - chmod +x ./build.sh 

  build:
  stage: build
  script:
    - sh build.sh
    
test:
  stage: test
  script:
    - npm run test-all
