image: node:10.21.0
stages:
   - build
   - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - apt-get -y install google-chrome-stable=80.0.3987.106
    - npm install -g @angular/cli@9.1.11
    - npm install
    - cd  /usr/bin/google-chrome && ls
    - chmod +x ./build.sh
    - node -v
    - if [ -f /.dockerenv ]; then echo "docker-executor"; fi
    - ls
    # - cd ./node_modules && ls
    # - cd ./.bin && ls 
    - bash build.sh
    - ls
    - cd ./dist && ls
    - cd bundles && ls
    - cd wmapp && ls
    - cd scripts && ls
    
test:
  stage: test
  script:
    - npm run test-all
