image: node:10.21.0
stages:
   - build
   - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install -g @angular/cli
    - npm install
    - chmod +x ./build.sh
    - node -v
    - if [ -f /.dockerenv ]; then echo "docker-executor"; fi
    - ./build.sh
    
test:
  stage: test
  script:
    - npm run test-all
