image: node:latest
stages:
   - build
   - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install -g @angular/cli
    - npm install
    - chmod +x ./build.sh
    - npm run shell-build
    
test:
  stage: test
  script:
    - npm run test-all
