image: node:10.21.0
stages:
   - build
   - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install -g @angular/cli@9.1.11
    - npm install
    - chmod +x ./build.sh
    - node -v
    - if [ -f /.dockerenv ]; then echo "docker-executor"; fi
    - ls
    - bash build.sh
    - ls
    # - cd ./dist && ls
    # - cd bundles && ls
    # - cd wmapp && ls
    # - cd scripts && ls
    - cd ./node_modules && ls
    - cd ./.bin && cd terser && ls
    
test:
  stage: test
  script:
    - npm run test-all
