stages:
        - jira_feature_dev
        - jira_next_release
        - jira_hotfix_release
        - jira_verification_merge
        - npm_test
        - notify

before_script:
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm'
  - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # Load nvm bash_completion'  

variables:
  NODE_OPTIONS: "--max-old-space-size=16384"    

jira_feature_dev:
  stage: jira_feature_dev
  tags:
      - jira
  only:
      - /^feature.*$/
      - /^dev.*$/
        
  script:
    - echo "$CI_COMMIT_MESSAGE" "$CI_COMMIT_BRANCH" "$JIRA_MSG" "$TOKEN" "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$NEXT_RELEASE_VERSION"
    - python3 /home/gitlab-runner/jira-ci-scripts/jira_connection.py "$CI_COMMIT_MESSAGE" "$CI_COMMIT_BRANCH" "$JIRA_MSG" "$TOKEN" 4 "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$NEXT_RELEASE_VERSION"
 
jira_next_release:
  stage: jira_next_release
  tags:
      - jira
  only:
    - next-release

  script:
    - echo "$CI_COMMIT_MESSAGE" "$CI_COMMIT_BRANCH" "$JIRA_MSG" "$TOKEN" "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$NEXT_RELEASE_VERSION"
    - python3 /home/gitlab-runner/jira-ci-scripts/jira_connection.py "$CI_COMMIT_MESSAGE" "$CI_COMMIT_BRANCH" "$JIRA_MSG" "$TOKEN" 5 "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$NEXT_RELEASE_VERSION"

jira_hotfix_release:
  stage: jira_hotfix_release
  tags:
      - jira
  only:
    - hotfix
  script:
    - echo "$CI_COMMIT_MESSAGE" "$CI_COMMIT_BRANCH" "$JIRA_MSG" "$TOKEN" "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$NEXT_HOT_FIX_VERSION"
    - python3 /home/gitlab-runner/jira-ci-scripts/jira_connection.py "$CI_COMMIT_MESSAGE" "$CI_COMMIT_BRANCH" "$JIRA_MSG" "$TOKEN" 5 "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$NEXT_HOT_FIX_VERSION"

jira_verification_merge:
  stage: jira_verification_merge
  tags:
    - jira
  only: [merge_requests]
  script:
    - echo "$CI_COMMIT_MESSAGE" "$CI_COMMIT_BRANCH" "$JIRA_MSG" "$TOKEN" "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" "$NEXT_HOT_FIX_VERSION"
    - python3 /home/gitlab-runner/jira-ci-scripts/verify_tickets_in_commits.py "$TOKEN" "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" "$CI_PROJECT_ID" "$GITLAB_TOKEN"

npm_test:
  stage: npm_test
  tags:
    - npm
  only:
    - merge_requests
  script:
    - node --version
    - npm --version
    - rm -rf /home/gitlab-runner/builds/wm-eng/wavemaker-ui-variables ; git clone --depth 1 https://oauth2:$GITLAB_TOKEN@gitlab.wavemaker.com/wm-eng/wavemaker-ui-variables.git /home/gitlab-runner/builds/wm-eng/wavemaker-ui-variables
    - cd /home/gitlab-runner/builds/wm-eng/wavemaker-ui-variables ; npm install ; npm install --save-dev @types/babel__core @types/babel__generator @types/babel__template @types/babel__traverse @types/graceful-fs @types/istanbul-lib-coverage @types/istanbul-lib-report @types/istanbul-reports @types/stack-utils @types/yargs @types/yargs-parser
    - npm run build 
    - cd ../wavemaker-ng-runtime
    - npm install 
    - npm i yalc -g
    - yalc add @wavemaker/variables
    - bash build.sh
    - bash bundle-runtime-cli.sh
    - echo "npm_test starting"
    - npm run test 
    - echo "npm_test finished $(date +%Y-%m-%d\ %H:%M:%S)"
    - date
  retry:
        max: 2
        when: stuck_or_timeout_failure
notify_job:
  stage: notify
  tags:
    - npm
  only:
    - merge_requests
  script:
    - apt-get update && apt-get install -y awscli
    - |
      if [ "$CI_JOB_STATUS" == "failed" ]; then
        MESSAGE="Pipeline failed in job: $CI_JOB_NAME on branch: $CI_COMMIT_REF_NAME."
      else
        MESSAGE="Pipeline succeeded in job: $CI_JOB_NAME on branch: $CI_COMMIT_REF_NAME."
      fi
      aws sns publish --topic-arn arn:aws:sns:us-east-1:365654357229:gitlab-pipeline --message "$MESSAGE"
  when: always
  dependencies:
    - npm_test


