export * from './variables.module';
export * from './services/calendar-service';
export * from './services/camera-service';
export * from './services/contacts-service';
export * from './services/datasync-service';
export * from './services/file-service';
export * from './services/scan-service';
export * from './services/device-service/device-service';
export * from './services/device-service/location-service';
