export * from './main';
export * from './app/app.module';
export * from './app/components/page-wrapper.component';
export * from './app/services/app-resource-manager.service';
export * from './app/services/app-extension.service';
export * from './app/services/app-js-provider.service';
export * from './app/services/app-variables-provider.service';
export * from './app/services/component-ref-provider.service';
export * from './app/services/prefab-config-provider.service';
