const rollupGlobals = {
    '@angular/animations': 'ng.animations',
    '@angular/common': 'ng.common',
    '@angular/common/http': 'ng.common.http',
    '@angular/compiler': 'ng.compiler',
    '@angular/core': 'ng.core',
    '@angular/core/primitives/signals': 'ng.signals',
    '@angular/core/primitives/event-dispatch': 'ng.event-dispatch',
    '@angular/forms': 'ng.forms',
    '@angular/platform-browser-dynamic': 'ng.platformBrowserDynamic',
    '@angular/platform-browser': 'ng.platformBrowser',
    '@angular/platform-browser/animations': 'ng.platformBrowser.animations',
    '@angular/router': 'ng.router',
    '@swipey': 'swipey',
    '@wavemaker/focus-trap': 'focusTrap',
    '@wavemaker/variables':'wm_common_variables',
    '@wavemaker/custom-widgets-m3':'wm_custom_widgets',
    '@wm/build-task': 'wm.buildTask',
    '@wm/core': 'wm.core',
    '@wm/transpiler': 'wm.transpiler',
    '@wm/components': 'wm.components',
    '@wm/components/base': 'wm.components.base',
    '@wm/components/input/base-form': 'wm.components.input.baseForm',
    '@wm/components/input/base-form-custom': 'wm.components.input.baseFormCustom',
    '@wm/components/input/dataset-aware-form': 'wm.components.input.datasetawareform',
    '@wm/components/input/caption-position': 'wm.components.input.captionposition',
    '@wm/components/input/button': 'wm.components.input.button',
    '@wm/components/input/button-group': 'wm.components.input.buttongroup',
    '@wm/components/input/checkbox': 'wm.components.input.checkbox',
    '@wm/components/input/checkboxset': 'wm.components.input.checkboxset',
    '@wm/components/input/composite': 'wm.components.input.composite',
    '@wm/components/input/number': 'wm.components.input.number',
    '@wm/components/input/radioset': 'wm.components.input.radioset',
    '@wm/components/input/select': 'wm.components.input.select',
    '@wm/components/input/switch': 'wm.components.input.switch',
    '@wm/components/input/text': 'wm.components.input.text',
    '@wm/components/input/textarea': 'wm.components.input.textarea',
    '@wm/components/input/calendar': 'wm.components.input.calendar',
    '@wm/components/input/chips': 'wm.components.input.chips',
    '@wm/components/input/color-picker': 'wm.components.input.colorpicker',
    '@wm/components/input/currency': 'wm.components.input.currency',
    '@wm/components/input/epoch/base-date-time': 'wm.components.input.epoch.baseDateTime',
    '@wm/components/input/epoch/date': 'wm.components.input.epoch.date',
    '@wm/components/input/epoch/date-time': 'wm.components.input.epoch.dateTime',
    '@wm/components/input/epoch/picker': 'wm.components.input.epoch.picker',
    '@wm/components/input/epoch/date-time-picker': 'wm.components.input.epoch.dateTimePicker',
    '@wm/components/input/epoch/time': 'wm.components.input.epoch.time',
    '@wm/components/input/file-upload': 'wm.components.input.fileupload',
    '@wm/components/input/rating': 'wm.components.input.rating',
    '@wm/components/input/slider': 'wm.components.input.slider',
    '@wm/components/basic/anchor': 'wm.components.basic.anchor',
    '@wm/components/basic/audio': 'wm.components.basic.audio',
    '@wm/components/basic/html': 'wm.components.basic.html',
    '@wm/components/basic/icon': 'wm.components.basic.icon',
    '@wm/components/basic/iframe': 'wm.components.basic.iframe',
    '@wm/components/basic/label': 'wm.components.basic.label',
    '@wm/components/basic/picture': 'wm.components.basic.picture',
    '@wm/components/basic/spinner': 'wm.components.basic.spinner',
    '@wm/components/basic/video': 'wm.components.basic.video',
    '@wm/components/basic/progress/progress-bar': 'wm.components.basic.progress.progressBar',
    '@wm/components/basic/progress/progress-circle': 'wm.components.basic.progress.progressCircle',
    '@wm/components/basic/progress/progress-utils': 'wm.components.basic.progress.progressUtils',
    '@wm/components/basic/rich-text-editor': 'wm.components.basic.richtexteditor',
    '@wm/components/basic/search': 'wm.components.basic.search',
    '@wm/components/basic/tree': 'wm.components.basic.tree',
    '@wm/components/data/card': 'wm.components.data.card',
    '@wm/components/data/form': 'wm.components.data.form',
    '@wm/components/data/list': 'wm.components.data.list',
    '@wm/components/data/live-table': 'wm.components.data.livetable',
    '@wm/components/data/pagination': 'wm.components.data.pagination',
    '@wm/components/data/table': 'wm.components.data.table',
    '@wm/components/chart': 'wm.components.chart',
    '@wm/components/containers/accordion': 'wm.components.containers.accordion',
    '@wm/components/containers/linear-layout': 'wm.components.containers.linearlayout',
    '@wm/components/containers/layout-grid': 'wm.components.containers.layoutgrid',
    '@wm/components/containers/panel': 'wm.components.containers.panel',
    '@wm/components/containers/tabs': 'wm.components.containers.tabs',
    '@wm/components/containers/tile': 'wm.components.containers.tile',
    '@wm/components/containers/wizard': 'wm.components.containers.wizard',
    '@wm/components/dialogs': 'wm.components.dialogs',
    '@wm/components/dialogs/confirm-dialog': 'wm.components.dialogs.confirmdialog',
    '@wm/components/dialogs/design-dialog': 'wm.components.dialogs.designdialog',
    '@wm/components/dialogs/alert-dialog': 'wm.components.dialogs.alertdialog',
    '@wm/components/dialogs/iframe-dialog': 'wm.components.dialogs.iframedialog',
    '@wm/components/dialogs/login-dialog': 'wm.components.dialogs.logindialog',
    '@wm/components/dialogs/partial-dialog': 'wm.components.dialogs.partialdialog',
    '@wm/components/navigation/breadcrumb': 'wm.components.navigation.breadcrumb',
    '@wm/components/navigation/menu': 'wm.components.navigation.menu',
    '@wm/components/navigation/navbar': 'wm.components.navigation.navbar',
    '@wm/components/navigation/popover': 'wm.components.navigation.popover',
    '@wm/components/advanced/carousel': 'wm.components.advanced.carousel',
    '@wm/components/advanced/login': 'wm.components.advanced.login',
    '@wm/components/advanced/marquee': 'wm.components.advanced.marquee',
    '@wm/components/advanced/custom': 'wm.components.advanced.custom',
    '@wm/components/page': 'wm.components.page',
    '@wm/components/page/footer': 'wm.components.page.footer',
    '@wm/components/page/header': 'wm.components.page.header',
    '@wm/components/page/left-panel': 'wm.components.page.leftpanel',
    '@wm/components/page/right-panel': 'wm.components.page.rightpanel',
    '@wm/components/page/top-nav': 'wm.components.page.topnav',
    '@wm/components/prefab': 'wm.components.prefab',
    '@wm/runtime/base': 'wm.runtime.base',
    '@wm/runtime/dynamic': 'wm.runtime.dynamic',
    '@wm/http': 'wm.http',
    '@wm/oAuth': 'wm.oAuth',
    '@wm/runtime': 'wm.runtime',
    '@wm/security': 'wm.security',
    '@wm/variables': 'wm.variables',
    '@metrichor/jmespath': 'jmespath',
    'ngx-bootstrap': 'ngx-bootstrap',
    'ngx-bootstrap/pagination': 'pagination',
    'ngx-bootstrap/utils': 'utils',
    'ngx-bootstrap/positioning': 'positioning',
    'ngx-bootstrap/component-loader': 'componentLoader',
    'ngx-bootstrap/focus-trap': 'focusTrap',
    'ngx-bootstrap/mini-ngrx': 'miniNgrx',
    'ngx-bootstrap/collapse': 'collapse',
    'ngx-bootstrap/tooltip': 'tooltip',
    'ngx-bootstrap/timepicker': 'timepicker',
    'ngx-bootstrap/chronos': 'chronos',
    'ngx-bootstrap/typeahead': 'typeahead',
    'ngx-bootstrap/progressbar': 'progressbar',
    'ngx-bootstrap/datepicker': 'datepicker',
    'ngx-bootstrap/modal': 'modal',
    'ngx-bootstrap/dropdown': 'dropdown',
    'ngx-bootstrap/popover': 'popover',
    'ngx-bootstrap/carousel': 'carousel',
    'ngx-bootstrap/accordion': 'accordion',
    'ngx-bootstrap/buttons': 'buttons',
    'ngx-bootstrap/rating': 'rating',
    'ngx-bootstrap/locale': 'locale',
    'ngx-bootstrap/sortable': 'sortable',
    'ngx-bootstrap/tabs': 'tabs',
    'ng-circle-progress': 'ngCircleProgress',
    'ngx-color-picker': 'ngxColorpicker',
    'angular-imask': 'angularIMask',
    "imask": "IMask",
    "lodash-es": "_",
    'ngx-toastr': 'ngxToastr',
    'rxjs': 'rxjs',
    'rxjs/operators': 'rxjs.operators',
    'tslib': 'tslib',
    'angular2-websocket/angular2-websocket': 'angularWebSocket'
};

export const rollupExternals = [
    '@angular/core',
    '@angular/compiler',
    '@angular/router',
    '@angular/common/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/platform-browser/animations',
    '@angular/animations',
    '@angular/common',
    '@angular/forms',
    '@angular/core/primitives/signals',
    '@angular/core/primitives/event-dispatch',
    '@metrichor/jmespath',
    '@swipey',
    '@wm/http',
    '@wm/core',
    '@wm/oAuth',
    '@wm/transpiler',
    '@wm/variables',
    '@wm/security',
    '@wm/build-task',
    '@wm/components/basic/anchor',
    '@wm/components/basic/audio',
    '@wm/components/basic/html',
    '@wm/components/basic/icon',
    '@wm/components/basic/iframe',
    '@wm/components/basic/label',
    '@wm/components/basic/picture',
    '@wm/components/basic/spinner',
    '@wm/components/basic/video',
    '@wm/components/basic/progress/progress-bar',
    '@wm/components/basic/progress/progress-circle',
    '@wm/components/basic/progress/progress-utils',
    '@wm/components/basic/rich-text-editor',
    '@wm/components/basic/search',
    '@wm/components/basic/tree',
    '@wm/components/dialogs',
    '@wm/components/dialogs/design-dialog',
    '@wm/components/base',
    '@wm/components/input/button', 
    '@wm/components/input/base-form',
    '@wm/components/input/base-form-custom',
    '@wm/components/input/dataset-aware-form',
    '@wm/components/input/caption-position',
    '@wm/components/input/button-group',
    '@wm/components/input/checkbox',
    '@wm/components/input/checkboxset',
    '@wm/components/input/composite',
    '@wm/components/input/number',
    '@wm/components/input/radioset',
    '@wm/components/input/select',
    '@wm/components/input/text',
    '@wm/components/input/textarea',
    '@wm/components/input/switch',
    '@wm/components/input/calendar',
    '@wm/components/input/chips',
    '@wm/components/input/color-picker',
    '@wm/components/input/currency',
    '@wm/components/input/epoch/base-date-time',
    '@wm/components/input/epoch/date',
    '@wm/components/input/epoch/date-time',
    '@wm/components/input/epoch/picker',
    '@wm/components/input/epoch/date-time-picker',
    '@wm/components/input/epoch/time',
    '@wm/components/input/file-upload',
    '@wm/components/input/rating',
    '@wm/components/input/slider',
    '@wm/components/data/card',
    '@wm/components/data/form',
    '@wm/components/data/list',
    '@wm/components/data/live-table',
    '@wm/components/data/pagination',
    '@wm/components/data/table',
    '@wm/components/chart',
    '@wm/components/containers/accordion',
    '@wm/components/containers/linear-layout',
    '@wm/components/containers/layout-grid',
    '@wm/components/containers/panel',
    '@wm/components/containers/tabs',
    '@wm/components/containers/tile',
    '@wm/components/containers/wizard',
    '@wm/components/dialogs/alert-dialog',
    '@wm/components/dialogs/iframe-dialog',
    '@wm/components/dialogs/login-dialog',
    '@wm/components/dialogs/partial-dialog',
    '@wm/components/dialogs/confirm-dialog',
    '@wm/components/navigation/breadcrumb',
    '@wm/components/navigation/menu',
    '@wm/components/navigation/navbar',
    '@wm/components/navigation/popover',
    '@wm/components/advanced/carousel',
    '@wm/components/advanced/marquee',
    '@wm/components/advanced/login',
    '@wm/components/advanced/custom',
    '@wm/components/page',
    '@wm/components/page/footer',
    '@wm/components/page/header',
    '@wm/components/page/left-panel',
    '@wm/components/page/right-panel',
    '@wm/components/page/top-nav',
    '@wm/components/prefab',
    '@wavemaker/focus-trap',
    '@wavemaker/variables',
    '@wavemaker/custom-widgets-m3',
    '@wm/runtime/base',
    '@wm/runtime/dynamic',
    '@wm/components/base',
    'imask',
    'angular-imask',
    'angular2-websocket/angular2-websocket',
    'rxjs',
    'rxjs/operators',
    'lodash-es',
    'ngx-bootstrap/collapse',
    'ngx-bootstrap/utils',
    'ngx-bootstrap/positioning',
    'ngx-bootstrap/component-loader',
    'ngx-bootstrap/timepicker',
    'ngx-bootstrap/chronos',
    'ngx-bootstrap/focus-trap',
    'ngx-bootstrap/mini-ngrx',
    'ngx-bootstrap/typeahead',
    'ngx-bootstrap/progressbar',
    'ngx-bootstrap/pagination',
    'ngx-bootstrap/modal',
    'ngx-bootstrap/tooltip',
    'ngx-bootstrap/datepicker',
    'ngx-bootstrap/dropdown',
    'ngx-bootstrap/popover',
    'ngx-bootstrap/carousel',
    'ngx-bootstrap/accordion',
    'ngx-bootstrap/buttons',
    'ngx-bootstrap/rating',
    'ngx-bootstrap/locale',
    'ngx-bootstrap/sortable',
    'ngx-bootstrap/tabs',
    'ngx-color-picker',
    'ngx-toastr',
    'ng-circle-progress',
    'tslib'
]

export default rollupGlobals;
